### ISSUE TITLE
New javaAction idea : GroupBy and count in a list 

### ISSUE THREAD

**Issue by NicolasBRUNAUD** [mendix/CommunityCommons#121]
i regularly implement a microflow to groupby and count my objects in a list.
Most of the time, it's about displaying an appealing UI and display a pie chart as a filter of a list.
I think it would worth to make it generic with a java action and include it in the community toolset.

input1 : list of objects
input2 : member name (as a string)
output : list of value pairs  (MemberValue+ Count)

loop until list is empty
 - take first object of the list 
 -  filter all object similar to first object where Member = ValueOfFirstObject
 - count
 - remove filtered objects from original list
 - create value pair
    - MemberValue : ValueOfFirstObject
    - Count: count

**Comment by grootjans** [comment]
We currently do not have other actions and operation for reporting purposes or aggregating object lists. Most uses cases in Mendix we would recommend to use OQL directly to get a data set that has the appropriate grouping, instead of operating on a list.
