### ISSUE TITLE
Problems with executeMicroflowAsUser_1

### ISSUE THREAD

**Issue by RCatersels** [mendix/CommunityCommons#13]
We are working in Mx5.16.1. I have upgraded the community commons module from 5.3 to 5.4. From this point I have some microflows that used executeMicroflowAsUser_1 and are no longer working in 5.4. When I debug the model just stops at the java action. No error is thrown but the microflow that should be executed is never reached when I set a breakpoint on that microflow. Now the microflow just stops and never quits.

Any suggestion on how to debug this? The java actions itself have not been changed between 5.3 and 5.4 so it most be some library issue. But I have nothing in my console. Will try to debug from Eclipse to see if I can get any clues from there. If you have any thought on why this is happening I would like to hear them.

Regards,

Ronald

**Comment by RoelandSalij** [comment]
We were not able to reproduce this behaviour in a small test project. Microflows are triggered as expected.

The microflow does work well when starting it manually with the required user account?

**Comment by RCatersels** [comment]
I could not reproduce it in a test project either. The microflow that is triggered has no security on it and can be run by anyone. There are some translations in that microflow, that is why I need the user context so I can apply his language. I reverted back to 5.3 and all was working again. I can give you our project, but as you know that is a big one. Let me know and I make all the files, database and steps on how to reproduce.

Regards,

Ronald

**Comment by RoelandSalij** [comment]
Hi Ronald,
The latest release contains a fix which 'touches' the ExecuteMicroflowAsUser methods. 
Does that fix your issue?
