### ISSUE TITLE
Duplicate file document and image methods do not close input streams

### ISSUE THREAD

**Issue by Erwin-t-Hoen** [mendix/CommunityCommons#15]
The methods duplicateFileDocument and duplicateImage open an inputstream to get the content of the files via the core.get method.
These inputstreams are however never closed, leaving a pointer to the file open.
When the methods are called from a microflow and the call is followed by a delete of the original filedocument or image the Mendix object will be delete but the file will remain available on the file system. The error recieved from the delete being performed by the server is not propagated to the microflow, so the user is not aware of any errors occuring. This will however lead to inconsistency where the Mendix objects are no longer available and the files remain, taking up more space then should be.
Please change the two methods in the Misc class to:

```
public static Boolean duplicateFileDocument(IContext context, IMendixObject toClone, IMendixObject target) throws Exception
	{
		if (toClone == null || target == null)
			throw new Exception("No file to clone or to clone into provided");
		
		 MendixBoolean hasContents = (MendixBoolean) toClone.getMember(context, FileDocument.MemberNames.HasContents.toString());
     if (!hasContents.getValue(context))
    	 return false;

		InputStream inputStream = Core.getFileDocumentContent(context, toClone); 
	
		try {
			Core.storeFileDocumentContent(context, target, (String) toClone.getValue(context, system.proxies.FileDocument.MemberNames.Name.toString()),  inputStream); 
			return true;
		} catch (Exception e) {
			e.printStackTrace();
		}
		finally{
			try {
				if(inputStream != null)
				inputStream.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		return true;
	}
	
  public static Boolean duplicateImage(IContext context, IMendixObject toClone, IMendixObject target, int thumbWidth, int thumbHeight) throws Exception
  {
      if (toClone == null || target == null)
          throw new Exception("No file to clone or to clone into provided");

      MendixBoolean hasContents = (MendixBoolean) toClone.getMember(context, FileDocument.MemberNames.HasContents.toString());
      if (!hasContents.getValue(context))
          return false;

      InputStream inputStream = Core.getImage(context, toClone, false); 

      try {
		Core.storeImageDocumentContent(context, target, inputStream, thumbWidth, thumbHeight);

		  return true;
	} catch (Exception e) {
		e.printStackTrace();
	}
      finally {
    	  try {
			if(inputStream!= null)
			  inputStream.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
      }
      return true;
  }
```

**Comment by mkrouwel** [comment]
When calling this method many times in a few hours (in our case several thousand of times per hour), this could lead to a Java.io.filenotfoundexception ('too many open files'). See http://mxforum.mendix.com/questions/11572/javaioFileNotFoundException-Too-many-open-files
Solution indeed is to properly close the inputstream
