### ISSUE TITLE
JodaTime needs update to newer lib

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/CommunityCommons#21]
With newer version of Java it has troubles converting some times...  [Bug](https://github.com/JodaOrg/joda-time/pull/291)

[AWS Time issue](http://shttp://stackoverflow.com/questions/34478117/aws-authentication-requires-a-valid-date-or-x-amz-date-header)

https://github.com/mendix/CommunityCommons/blob/master/src/userlib/joda-time-1.6.2.jar
is more than 2 years old... 

Please update to the latest lib. [Releases](https://github.com/JodaOrg/joda-time/releases)

**Comment by RoelandSalij** [comment]
Fixed in https://github.com/mendix/CommunityCommons/releases/tag/v6.1
