### ISSUE TITLE
Split up Community Commons

### ISSUE THREAD

**Issue by RoelandSalij** [mendix/CommunityCommons#24]
We want to split up this module into smaller 'Mendix connectors'.
By splitting up this module into smaller modules/connectors people don't end up with everything while they might only be interested in a small part.

I'm interested what the community think of this idea.(e.g. @Andries-Smit , @mgroeneweg, @RCatersels, @kimpellikaan)  
My proposal is to split this module up to the following (this is based on what's currently available. Need to determine what still makes sense or not and how stuff is connected):

Object handling
- Clone
- CopyAttributes
- DeepClone
- DeleteAllObjects
- CommitInSeparateDatabaseTransaction
- DeleteInSeparateTransaction **(NEW)**
- DeleteWithoutEvents **(NEW)**
- CreateListFromObject **(NEW)**
- CommitWithoutEvents
- EncryptMemberIfChanged
- End Transaction
- GetCreatedByUser
- GetGuid
- GetLastChangedByUser
- GetOriginalValueAsString
- GetTypeAsString
- MemberHasChanged
- ObjectHasChanged
- ~~ObjectIsNew~~
- ~~RefreshClass~~
- RefreshClassByObject
- StartTransaction
- Xpath.java

Regular expressions
- EmailAddress
- GuidOrEmpty
- Guid
- Identifier

String operations
- Base64Decode
- Base64Encode
- DecryptString
- EncryptString
- EscapeHTML
- GenerateHMAC_SHA256_hash
- Hash
- HTMLEncode
- HTMLToPlainText
- IsEmptyString
- IsNotEmptyString
- RandomHash
- RandomString
- RandomStrongPassword
- RegexQuote
- RegexReplaceAll
- RegexTest
- StringLeftPad
- StringRightPad
- StringLength (TO REMOVE)
- StringTrim
- SubstituteTemplate
- SubstituteTemplate2
- XSSSanitize

DateTime
- DatePartSelector
- DateTimeToLong
- GetIntFromDateTime
- LongToDateTime
- ParseDateTimeWithTimeZone
- YearsBetween

ExecuteMicroflow
- ExecuteMicroflowAsUser
- ExecuteMicroflowAsUser_1
- ExecuteMicroflowAsUser_2
- ExecuteMicroflowInBackground
- ExecuteMicroflowInBatches
- RecommitInBatches
- RunMicroflowAsyncInQueue

File
- Base64DecodeToFile
- Base64EncodeFile
- DuplicateFileDocument
- DuplicateImageDocument
- FileDocumentFromFile
- FileFromFileDocument
- GetFileContentsFromResource
- GetFileSize
- StoreURLToFileDocument
- StringFromFile
- StringToFile
- GetImageDimensions (Pull request Webflight)

PDF
- MergeMultiplePDF
- OverlayPDFDocument

Logging
- Log
- LogLevel
- SimpleLog
- TimeMeasureEnd
- TimeMeasureStart

MendixCore
- GetApplicationURL
- GetDefaultLanguage
- GetRuntimeVersion
- IsInDevelopment

Exceptions
- ThrowException
- ThrowWebserviceException

Test
- AssertTrue (REMOVE, I think AssertTrue_2 is more valuable is the one people like to use anytime )
- AssertTrue_2
-  DeepObjectAssert ( Pull Request Webflight)

**Comment by kimpellikaan** [comment]
My thoughts exactly! 

An additional idea, should the test component exist in the CC? Or should the Unit test module become more active? 

Then again, the same can be said for quite allot of JA's. E.g. Encryption. Maybe it's not a big deal.

**Comment by mgroeneweg** [comment]
Great idea!

**Comment by RoelandSalij** [comment]
@kimpellikaan, glad you mention that. It indeed crossed my mind to move it to the Unit test module too. (I think those functions are the reason why UnitTesting depends on CommunityCommons). The test part is rather small now and I'm not really sure if there are any use cases in the real world which do not relate to testing.

**Comment by RCatersels** [comment]
Good suggestion, but I would even want to take a view in a even further perspective. I always assumed that some of these actions would eventually wind up in the modeler. Take for instance the YearsBetween function. It is simply an omission that this function is not available in the modeler while we have all kind of other Between date function calls. 
The ExecuteMicroflow functions could may be split up. Move everything that has to do with queue to the Process Queue appstore module and it would be so nice if the run as user part could end up in the modeler as a parameter option of a microflow. 
To make my point, yes it is good to split everything up but I also would like a fundamental discussion why actions that are used so often do not end up in the modeler.

**Comment by RoelandSalij** [comment]
Ronald thanks for your comment. I totally agree with your suggestion and this is indeed a conversation I am planning to have with our R&D department. 
However, before R&D is involved in this project the first step is to simply start splitting up this module into smaller parts and figure out what would be logical to provide in the platform by default from a functional perspective and that's what I have started with now.

IMO at this stage it's not a case of discussing 'if' it should be done but 'what' will be done. Please share which functions would make sense to adopt in the platform according to the community, as I am restricted to my personal opinion now :)

Exposing these java actions as microflow actions will already greatly improve the user experience an results in a more 'native plaform' feel. Your (advanced) function toolbox will be modular and on-demand.

**Comment by grootjans** [comment]
Though we still agree there are merits to modularizing the Community Commons, we expect to shift our focus to integrating more of CC into the core platform. Though some time ago, and example of that was integrating the functions calendarMonthsBetween, calendarYearsBetween, dateTimeToEpoch, and epochToDateTime as microflow expression functions into the platform. If we do split in the future, it would be sensible to open the discussion again.
