### ISSUE TITLE
communitycommons\Misc.java:656: error: unreported exception COSVisitorException

### ISSUE THREAD

**Issue by Nay3ls** [mendix/CommunityCommons#27]
I've upgraded from 6.10.0 to 6.10.2.  I get an error with community commons when I try to build. This is the error

```java
compile:
    [javac] Compiling 407 source files to D:\Projects\ProjectName\deployment\run\bin
    [javac] D:\Projects\ProjectName\javasource\communitycommons\Misc.java:656: error: unreported exception COSVisitorException; must be caught or declared to be thrown
    [javac] 		overlay.overlay(new HashMap<Integer, String>()).save(baos);
    [javac] 		                                                    ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: D:\Projects\ProjectName\javasource\com\mendix\core\Core.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error



BUILD FAILED
D:\Projects\ProjectName\deployment\build_core.xml:27: Compile failed; see the compiler error output for details.

Total time: 10 seconds
```

**Comment by RoelandSalij** [comment]
Thanks for your feedback! Do I understand you correct and did you:
- upgrade your project to 6.10.2
- not update the Community Commons module from the App Store.
Resulting in this compile error?

**Comment by Nay3ls** [comment]
@RoelandSalij  I updated the project to 6.10.2 and updated the community commons module.
I also cleaned my deployment folder.

**Comment by RoelandSalij** [comment]
Thanks, I was curious if this problem is a result of the conversion of your project to 6.10.2 or the result of updating the module.
Can you share from which modeler version you did migrate?

**Comment by Nay3ls** [comment]
@RoelandSalij  I migrated from version 6.10.0 as I stated before

**Comment by RoelandSalij** [comment]
My mistake, I meant module version. 
(You can find the version number in the Community Commons Module as the title of a folder.)

**Comment by Nay3ls** [comment]
_Community Commons 6.1 for Mx 6.0.1

**Comment by RoelandSalij** [comment]
Which PDFbox related jar files do you have located in in your userlib folder (you can find this folder in your Mendix project folder)?
Do you have 'pdfbox-1.8.5.jar' and 'pdfbox-app-2.0.3.jar'?

**Comment by Nay3ls** [comment]
Yes I have both files!

**Comment by RoelandSalij** [comment]
Ok, I suspect there is a conflict with both libraries.
Can you please remove 'pdfbox-1.8.5.jar' and try to rebuild your project? Does that help?

**Comment by Nay3ls** [comment]
That fixed it! Thanks!

**Comment by RoelandSalij** [comment]
Thank you for your swift response!

**Comment by isamu-tanaka** [comment]
It's the same issue.  We had this problem in two customer's projects.  It is better to document it for the customers.
The 'pdfbox-1.8.5.jar' was removed and fixed but a document is needed.
