### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by RCatersels** [mendix/CommunityCommons#30]
We have a couple of Java action that are missing in the documentation:
commitInSeparateDatabaseTransaction
StartTransaction
EndTransaction

I noticed this because my assumption about StartTransaction and EndTransaction seemed to be wrong. My assumption was that everything in between would end up in the database before the microflow ends. But this seems not to be the case. 
Regards,
Ronald

**Comment by RoelandSalij** [comment]
Added.
EndTransaction should be used first before starting a new transaction.
