### ISSUE TITLE
Java compilation errors when running in Mendix 7.5.0

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/CommunityCommons#37]
When creating a new Mendix 7.5.0 app (with Asset Manager theme) compilation fails when running the app:

```
C:\Users\paulk\Documents\Mendix\App\javasource\communitycommons\Misc.java:660: error: unreported exception COSVisitorException; must be caught or declared to be thrown
    [javac] 		overlay.overlay(new HashMap<Integer, String>()).save(baos);
    [javac] 		                                                    ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error
```

**Comment by RoelandSalij** [comment]
Thanks for the feedback.
This isn't an issue in Community Commons. The Atlas Starter apps are including old libraries, causing a conflict preventing apps to compile in combination with Community Commons.
These libraries shouldn't be included in these starter apps at all.
@eheddema
