### ISSUE TITLE
GetImageDimensions input parameter compile error (mismatch between parameter name in modeler and java)

### ISSUE THREAD

**Issue by martijnraats** [mendix/CommunityCommons#38]

**Comment by RoelandSalij** [comment]
Hi Martijn, 
The java action parameter in the modeler is `image`. The one it generates for the java action is `ImageParameter1` as Image is implicitly reserved as there is an entity  which is named `Image`. 
Hence the renaming. This shouldn't cause any issue though.

In which Modeler version is this occurring?

**Comment by martijnraats** [comment]
I add the community commons in a 7.5.0 project and run it. Then I get a compile error.

**Comment by RoelandSalij** [comment]
Did you start a new app/project or did you convert an existing project? In case you started a new app, which one specifically?

I can't reproduce the issue in this project so I'm looking for the exact reproduction steps.

**Comment by martijnraats** [comment]
I can't reproduce either anymore. I did import it in an existing project. I think better to close this issue then.
