### ISSUE TITLE
Translating PR (README) in to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [mendix/CommunityCommons#47]
HI! I would like to contribute with this project by offering a translation in to Spanish (my native language) I can translate any PR you want. I work for Utopian-io as translator. Let me know if interested!

**Comment by RoelandSalij** [comment]
Hi Luigi.
This module is by the community and for the community. 
I you feel that you can make a contribution that benefits our community, please create a pull request.
Thanks!
