### ISSUE TITLE
ConcurrentHashMap should be stored in database.

### ISSUE THREAD

**Issue by isamu-tanaka** [mendix/CommunityCommons#50]
Mendix is a stateless server.  ConcurrentHashMap should be stored in database.
The current implementation is just a session-based concurrency control.

**Comment by recktenwaldfabian** [comment]
As this topic was closed in the Idea forum:
A ConcurrentHashMap by itself has no need to be stored in the database. On the other hand, for a proper locking mechanism the current implementation using the ConcurrentHashMap is no longer suitable for larger Mendix Apps. You should probably explain that issue in more detail: i.e. that there is a need for a working locking mechanism in Mendix.

**Comment by isamu-tanaka** [comment]
PROBLEM: For the current implementation of CommunityCommons, then changing the same one object of Entity by two different browsers (ie. Chrome and FireFox) with different sessions cannot be detected.
I agree that there might be a better solution if you are saying about 'Concurrent execution' property of Microflow, instead of ConcurrentHashMap.  I confirmed that 'Concurrent execution' is not session-based.
