### ISSUE TITLE
Change to interface of ExecuteMicroflow actions

### ISSUE THREAD

**Issue by ollyspooner** [mendix/CommunityCommons#55]
Community Commons Function Library v7.0.0 changes the parameter for the ExecuteMicroflow actions specifying the MF from a string to a specified microflow. This dramatically changes the utility of the action as you can no longer use it to launch an arbitrary MF. This seems very bad practice and should have failed any unit testing of the module prior to release, assuming any has been done. 
I am not even sure I understand why it was done, given the risk of breaking so many dependencies. Please can you urgently reconsider this change?

**Comment by RoelandSalij** [comment]
Hi Olly,
Thanks for the feedback. 
What Robert writes, keeping the model consistent, is exactly the intended improvement. Using strings instead makes it error prone.

What's exactly the use case that you would like to facilitate by executing microflows by string?

**Comment by ollyspooner** [comment]
Hi Roeland,
Providing the microflow name as a string allows the microflow to be executed without prior knowledge of the exact microflow to be used at design time. This is particularly useful to me to create a flexible method to integrate a common module into a variety of apps by providing a callback microflow that can be specified in a constant.
I appreciate that this was probably only an unintended usage of the action, but I also note that at least one other has had an issue with this change, as they have left a note in the App Store reviews.

**Comment by ollyspooner** [comment]
Hi again Roeland,
Just to say that I have been made aware via the forum thread (https://forum.mendixcloud.com/link/questions/89454) of the policy to allow breaking API changes on major version change. This does take the edge of my (slightly ranty, sorry) argument. I still feel that the abstraction utility afforded by the old interface is a useful feature, but maybe in a new action? If there is only a small fan base for such an action, then I completely understand not including it in CommunityCommons and I will keep my own version of the action for that use.

**Comment by RoelandSalij** [comment]
Thanks! Makes sense, I can add some extra actions to serve that purpose.
Would like to keep the ones with microflows as parameters the default, though.
