### ISSUE TITLE
Regex for email has performance issues (repetitive alternative paths)

### ISSUE THREAD

**Issue by stephanbruijnis** [mendix/CommunityCommons#70]
Hi there,

The older versions of CommunityCommons have a regular expression for emails like this:
`\w+((-|+|.)\w+)@\w+([.-]?\w+)(.\w{2,6})+`

_Edit: it seems this has issues too:_
`Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 7
\w+((-|+|.)\w+)@\w+([.-]?\w+)(.\w{2,6})+` 

The newer version has this `\w+((-|\+|\.)\w+)*@\w+([\.-]?\w+)*(\.\w{2,})+` as regex. Containing repetitive alternative paths, the performance of this expression is really poor compared to the earlier version, also it has the tendancy to keep running forever on e-mailadresses like: test@test.comcomcomcomcomcomcomcomcom

Is there really a need for these alternative paths? 

See also: https://stackoverflow.com/questions/7509905/java-lang-stackoverflowerror-while-using-a-regex-to-parse-big-strings

With kind regards,
Stephan

**Comment by reinouts** [comment]
Hi Stephan,

There's not one "best" regular expression from emails. Is there a regular expression that you know of that performs better without sacrificing quality?

**Comment by stephanbruijnis** [comment]
I think there is no best regular expression for emails. Email validation via regular expressions don't work very well. Imho if you want to use a regex it should be: contains an @ and contains a . after the @. Everything else is likely to give false positives. 

Either keep e-mail validation very simple (check for @ and . ) or more advanced by actually sending an email with validation link or use an 3rd party service that uses mail server verification. 

The point of the issue raised here; the older regex performs better than the newer version, and I don't see the need for the newer version.

**Comment by reinouts** [comment]
But you say there's issues with the older version as well, so I don't think reverting is the way to go.

**Comment by markfilan** [comment]
The fully RFC 822 compliant regex is inefficient and obscure for [validate email address](http://net-informations.com/js/progs/email.htm) because of its length. Fortunately, RFC 822 was superseded twice and the current specification for email addresses is RFC 5322. RFC 5322 leads to a regex that can be understood if studied for a few minutes and is efficient enough for actual use.

If you use HTML5, use this code:

`<input type="email" name="email" required placeholder="Enter a valid email address">`

**Comment by grootjans** [comment]
Given that we have not received a lot more comments or suggestions on the old/new regex validation we will not do a rollback. Though RFC 5322 superseded RFC 822 and might be less obtuse, I fail to find an authoritative source for a regular expression for this.
