### ISSUE TITLE
stringToFile and stringFromFile both use UTF-8

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/CommunityCommons#75]
StringToFile and StringFromFile both use UTF-8, which is not working with PDF files. If instead it would use ISO-8859-1, it would work properly, I tried it. The weird thing is, the PDF file is generated without errors, but is blank.
If, on the other hand, the intended purpose of those functions is to work only with _text_ files, this should be specified in the documentation of those Java Actions; and add similar actions for _binary_ files.

**Comment by reinouts** [comment]
I looked into this and noted the documentation in the 'StringFromFile' action: 

> Note that this might give strange results when using with binary files. In that case, use the Base64 functions.

So I'm going to assume this behavior is intentional. If you have trouble using the Base64 functions, please file a separate issue. Thanks!

**Comment by dan-covaliu** [comment]
The results of StringFromFile, when used with PDF files, are not merely "strange", it's just that UTF-8 is hard coded inside. PDF files are not Base64-encoded. Base64 is a weak encoding of text information. Maybe we need a version of those JA where you could specify the encoding. Or PDFTo/FromFile.

**Comment by reinouts** [comment]
Hi Dan, 

If you'd like to create a PR where the two actions take an (optional) charset parameter I'd be willing to review and eventually merge it.

**Comment by dan-covaliu** [comment]
Thank you Reinout,

I did a PR. Fair warning though, I’m not a Java person, so feel free to review and rectify the changes as you see fit. Cheers!

Regards, | Cordialement,

Dan Covaliu
Software Integrator and Designer | Intégrateur et concepteur de logiciel
T  514-496-1479     F 514-496-9344

bdc.ca<http://www.bdc.ca/EN/Pages/home.aspx?utm_campaign=signature&utm_medium=email&utm_source=signature>
