### ISSUE TITLE
GetRuntimeVersion incompatible with Mendix 8

### ISSUE THREAD

**Issue by heuvelc** [mendix/CommunityCommons#83]
This java actions fails in Mendix 8 with an null pointer exception.

**Comment by reinouts** [comment]
I have tried to reproduce this but it works for me. Could you download the attached file, rename it from .zip to .mpk, import it in Mendix 8 beta 2 and tell me if it works for you as well? Can you make a testcase where it fails?
[GetRuntimeVersion.zip](https://github.com/mendix/CommunityCommons/files/3305304/GetRuntimeVersion.zip)

**Comment by heuvelc** [comment]
This works for me too and a new (test)project also. So the issue is with the live project converted from Mendix 7.23.4 to Mendix 8. I will dig into it to see if I can find the root cause am keep you posted.

**Comment by reinouts** [comment]
@heuvelc I've released version 8.0.1 where I am using the LogNode enum's name instead of caption. Could you try if this solves your issue?

**Comment by heuvelc** [comment]
The update works like a charm. Tested in in multiple projects in Mendix 8 both new and updated from Mx 6 and 7. Case closed, thanks a lot for the quick response.
