### ISSUE TITLE
Do not deprecate RegexReplaceAll as it is not an exact match for ReplaceAll

### ISSUE THREAD

**Issue by robertprice** [mendix/CommunityCommons#88]
RegexReplaceAll is marked for deprecation as it duplicates ReplaceAll. 

RegexReplaceAll offers greater functionality than ReplaceAll as it supports capture variables such as $1, $2, etc that the standard ReplaceAll function in Mendix does not support. 

This is useful functionality, and I don't think we should deprecate this function until ReplaceAll can also do this.

**Comment by reinouts** [comment]
You are correct; I checked with the AppDev teams and it is not planned to add this option to the default ReplaceAll function. So I will remove the deprecation.

**Comment by reinouts** [comment]
Fixed in 8.2.0.
