### ISSUE TITLE
Hash fails on small inputs

### ISSUE THREAD

**Issue by mweststrate** [mendix/CommunityCommons#9]
See https://mxforum.mendix.com/questions/7450/Community-Commons-Hash-Error-Output-buffer-too-small

**Comment by tieniber** [comment]
Hash() currently returns incorrect data. The main hashing operation is using an overload that returns an int instead of the hashed byte array. A corrected version is:

	public static String hash(String value, int length) throws NoSuchAlgorithmException, DigestException
	{
		byte[] inBytes = value.getBytes();
		byte[] outBytes = new byte[length];
		
		MessageDigest alg=MessageDigest.getInstance(HASH_ALGORITHM);
		alg.update(inBytes);
		
		alg.digest(outBytes, 0, length);
		return String.valueOf(outBytes);
	}
